// Backend configuration for TrustLedger frontend.
//
// Values mirror src/integrations/supabase/client.ts (auto-generated by the
// framework — never edit that file directly). If the backend is ever
// reconnected with new values, re-check this file against client.ts.
export const SUPABASE_URL =
  "https://spb-t4ne5rva952iw5o4.supabase.opentrust.net";

export const SUPABASE_PUBLISHABLE_KEY =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG5lNXJ2YTk1Mml3NW80IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODk3NzExMjgsImV4cCI6MjEwNTM0NzEyOH0.B6DTMT7OCFHOUD3zVOMJAKHOoo9x43_8w4Yn1c-7GjM";
